scriptname _CampfireInternalAPI extends Quest

Keyword property MagicDamageFire auto
Keyword property MagicDamageFrost auto
ReferenceAlias property IllegalItem1 auto
ReferenceAlias property IllegalItem2 auto
ReferenceAlias property IllegalItem3 auto
Message property _Camp_ObjectMainMenu auto
Message property _Camp_NotInitializedError auto
Quest property _Camp_CampingCrimeTracking auto
Quest property CampfireStrings auto
