scriptname _Camp_InstinctsArrowSearchController extends _Camp_InstinctsSearchController

EffectShader property _Camp_VisionStaticShader auto

function DetectionGainedAction(ObjectReference akReference)
	_Camp_VisionStaticShader.Play(akReference)
endFunction

function DetectionLostAction(ObjectReference akReference)
	_Camp_VisionStaticShader.Stop(akReference)
endFunction

function CleanUpAction(ObjectReference akReference)
	_Camp_VisionStaticShader.Stop(akReference)
endFunction
