scriptname _DE_Visualize_Campsite_Trigger extends ObjectReference

GlobalVariable property _Camp_CurrentlyPlacingObject auto

Event OnActivate(ObjectReference akActionRef)
	_Camp_CurrentlyPlacingObject.SetValue(1)
endEvent