scriptname _DE_Visualize_Campsite_Trigger extends ObjectReference

GlobalVariable property _DE_CampsitePlacementOn auto

Event OnActivate(ObjectReference akActionRef)
	_DE_CampsitePlacementOn.SetValue(1)
endEvent