scriptname FrostfallAPI extends Quest

_Frost_Compatibility property Compatibility auto
_Frost_HeatSourceSystem property HeatSource auto
Actor property PlayerRef auto
Formlist property _Frost_WorldspacesExteriorOblivion auto
Formlist property _Frost_OvercastWeatherList auto
GlobalVariable property _Frost_WetLevel auto
GlobalVariable property _Frost_ExposureLevel auto