scriptname LastSeedAPI extends Quest

_Seed_VitalitySystem property Vitality auto
_Seed_HungerSystem property Hunger auto
_Seed_ThirstSystem property Thirst auto
_Seed_FatigueSystem property Fatigue auto
_Seed_VitalityMeterInterfaceHandler property VitalityMeterHandler auto
_Seed_HungerMeterInterfaceHandler property HungerMeterHandler auto
_Seed_FoodDatastoreHandler property FoodDatastore auto
_Seed_SpoilSystem property Spoil auto
_Seed_Compatibility property Compatibility auto

GlobalVariable property _Seed_APIVersion auto
GlobalVariable property _Seed_LastSeedVersion auto
GlobalVariable property _Seed_IsPlayerFocused auto

GlobalVariable property _Seed_HungerLevel auto
GlobalVariable property _Seed_ThirstLevel auto
GlobalVariable property _Seed_FatigueLevel auto
GlobalVariable property _Seed_VitalityLevel auto

ReferenceAlias property EventEmitter_LastSeedLoaded auto